[package]
name = "include-doc"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "Include examples in your Rustdocs."
keywords = ["documentation", "examples", "rustdoc"]
readme = "../../README.md"

[dependencies]
include-doc-macro = { workspace = true }

[dev-dependencies]
trybuild.workspace = true
